### PR TITLE
Styles Mod

### PR DESCRIPTION
**Pull request by dominicOT**
add your image to your section and correct info about yourself @daudalile @solomonx-star #5

### CODE REVIEW

**Review by Ace-of-Space — APPROVED** [review]
👍👍

**Comment by Ace-of-Space** [comment]
@solomonx-star @daudalile add your pic and descrptn -  #9

**Comment by daudalile** [comment]
pic and description. were?

**Comment by dominicOT** [comment]
To the HTML file.
Check the section that contains team bio

**Pull request merged**
